services:
  db:
    image: postgres:17-alpine
    container_name: servicore-db
    environment:
      POSTGRES_USER: user_servicore
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: servicore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
