
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${PORT}/${NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=${update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


spring.flyway.enabled=false
spring.main.allow-circular-references=true

spring.profiles.active=${SPRING_PROFILES_ACTIVE}